development:
  adapter: postgresql
  encoding: unicode
  database: reactdb1
  pool: 5
  username: sunny
  password: password

production:
  url: postgresql://postgres:iLLSxMDPXDaayDQxLjLLBQppdrIyhttm@postgres.railway.internal:5432/railway
